version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: roombooking-db
    restart: always
    environment:
      MYSQL_DATABASE: roombooking
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  laravel:
    build:
      context: ./roombooking
    container_name: roombooking-app
    ports:
      - "8000:80"
    volumes:
      - ./roombooking:/var/www/html
      - ./roombooking/.env:/var/www/html/.env
    depends_on:
      - db

  roomservice:
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    container_name: roomservice-api
    ports:
      - "5000:8080"

    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Port=3306;Database=roombooking;User=user;Password=secret;"

  gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "7000:8080"
    depends_on:
      - roomservice
      - laravel
    volumes:
      - ./api-gateway/ocelot.json:/app/ocelot.json

volumes:
  db_data:
